// This is a script to read the mixed state dump files generated by the fixing bonding method 
// and copy and edit it to make it a valid data file for running segregation of a particular architecture.

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>

#include "../../../../../Scripts/System_File_Paths/system_file_paths.h"
#include GENERAL_FILE_METHODS

// global variables:
char* mixed_file_directory;
char* destination_directory;
char* architecture;
int numberOfMonomers;
int runNumber;
int numberOfMandatoryArguments = 2;
bool useSingleInitialState = false; // a flag that becomes true when the runNumber optional argument is passed to this script; This saves only a single; and in a initial state in a separate directory

int numberOfCrossLinks; // the number of crosslinks needed to make to Arc0 to make the current architecture
int** crossLinks; // double dim array to store the monomer indices that need to be crosslinked

// Sets the values of the global constant variables based on the arguments passed
void SetConstants(int argc, char** argv)
{
    if(argc < numberOfMandatoryArguments + 1) // number of arguments passed is less than expected
    {
        printf("Not enough arguments passed! Please pass the architecture(string) and the number of monomers(int) as arguments from the command line\nFor example:\n./createInitialStateExecuatable.out Arc2 200\n");
        printf("An optional argument for the particular run number can also be passed after the mandatory arguments if desired\n");
        exit(1);
    }
    else
    {
        //assuming atleast two arguments were passed; aprat from the default program name
        architecture = argv[1]; // the first argument after the program name
        numberOfMonomers = atoi(argv[2]); // the second argument after the program name
        //atoi(char*) is a function that takes an argument and returns the int expressed as the chaarcter string. If the characters are not a number, it returns 0
        if(numberOfMonomers == 0)
        {
            printf("Second argument \"%s\" passed was not a valid value for number of monomers! Please pass a valid integer\n", argv[2]);
            exit(1);
        }
    }

    SetDirectoryPath(&mixed_file_directory, CREATE_INITIAL_STATES, numberOfMonomers);
    SetDirectoryPath(&destination_directory, NEW_SEGREGATION, numberOfMonomers);
    // getting optional argument
    runNumber = GetRunIndex(argc, argv, numberOfMandatoryArguments);
    if(runNumber != -1)
        useSingleInitialState = true;
}


//returns the number of iteration at which a the mixed state with the runNumber was dumped
int GetMixedStateIteration(int runNumber)
{
    // the simulation starts with a 1000 step MC simulation, followwed by a 10^7 step relaxation, and then (runNumber-1) periods of 5*10^6 steps each
    // 1 step added for offset
    int MC_steps = 1000;
    int initial_relaxation_steps = pow(10, 7);
    int relaxation_interval = 5 * pow(10, 6);
    return MC_steps + initial_relaxation_steps + (runNumber - 1) * relaxation_interval + 1;
}

//Sets the file name of the mixed state dump with the passed runNumber at the specified string pointer
void SetMixedStateFileName(char** fileNamePointer, int runNumber, bool includeIterationNumber)
{   
    int bytes = 0;
    if(includeIterationNumber)
    {
        int iteration = GetMixedStateIteration(runNumber);
        bytes = asprintf(fileNamePointer, "mixed_state_%.2i_%i.txt", runNumber, iteration);
    }
    else
        bytes = asprintf(fileNamePointer, "mixed_state_%.2i.txt", runNumber);
    
    if(bytes == -1)
    {
        printf("Memory could not be allocated for the Mixed State File Name!\n");
        exit(1);
    }
}

//Sets the read file path in the mixed state directory
void SetReadFilePath(char** filePathPointer, int runNumber)
{
    char* fileName;
    if(numberOfMonomers == 200) // the naming scheme for the 200 monomer mixed state files contains the iteration number
        SetMixedStateFileName(&fileName, runNumber, true);
    else // the naming scheme for the 500 monomer mixed state files does not contain the iteration number
        SetMixedStateFileName(&fileName, runNumber, false);
    Append(filePathPointer, "", mixed_file_directory, fileName);
}

//Sets the write file path in the destination directory
void SetWriteFilePath(char** filePathPointer, int runNumber)
{
    char* folderName;
    char* fileName = "initial_configuration.txt";
    char* prefix;
    if(useSingleInitialState)
        Append(&prefix, architecture, "_", "singleInitialState");
    else
        prefix = architecture;

    SetFolderName(&folderName, prefix, runNumber);
    Append(filePathPointer, destination_directory, folderName, fileName);
}

//Sets the cross links database file name based on the global number of monomers variable
void SetDatabaseFileName(char** fileNamePointer)
{
    int bytes = asprintf(fileNamePointer, "b%i/Arc_Cross_Links_%i.txt", numberOfMonomers, numberOfMonomers);
    if(bytes == -1)
    {
        printf("Memoery could not be allocated for the database file name!\n");
        exit(1);
    }
}

//Allocates memory for the cross links array according to number of cross links present in the architecture
void AllocateCrossLinks(int noOfCrossLinks)
{
    crossLinks = (int**) malloc(sizeof(int*) * noOfCrossLinks);
    for(int i = 0; i < noOfCrossLinks; i++)
        crossLinks[i] = (int*) malloc(sizeof(int) * 2);
}

// Reads the Architecture Crosslinks database and updates numberOfCrossLinks and crossLinks
void ReadCrosslinks(void)
{
    char* databaseFile; // relative filePath
    SetDatabaseFileName(&databaseFile);
    FILE* filePointer;
    if((filePointer = fopen(databaseFile, "r")) == NULL)
    {
        printf("Cross Links Database file could not be opened!\n");
        exit(1);
    }

    bool hasArchBeenFound = false;

    int buffer = 500;
    char line[buffer];
    while(!hasArchBeenFound) // reading all lines till the architecture is found
    {
        fgets(line, buffer, filePointer);

        //checking if EOF is reached:
        if(feof(filePointer) != 0)
            break; //exiting the loop

        if(line[0] == '#' || line[0] == '\n') // comment line or blank line
            continue;
        else // must have encountered an architecture line
        {
            int len = strlen(architecture); // length of architecture string
            char arch[len + 1]; // setting size = len(architecture) + 1; last space for terminating char
            int noOfCrossLinks; // local copies of the architecture and crosslink variables

            //extracting the architecture from the line:
            strncpy(arch, line, len); // only extracting as many chars as present in architecture, since for a match, the lengths must be same anyway
            //this should not give false positive matches as long as names such as Arc2-2 occur after Arc2
            arch[len] = '\0'; // setting last char as terminating character

            sscanf(line, "%*s %i", &noOfCrossLinks); // parsing the line contents

            if(strcmp(arch, architecture) == 0) // architecture found
            {
                // reading the cross links into the array:
                AllocateCrossLinks(noOfCrossLinks); // allocating memory for cross links
                for(int i = 0; i < noOfCrossLinks; i++)
                {
                    fscanf(filePointer, "%i %i\n", &crossLinks[i][0], &crossLinks[i][1]); // scanning monomer indices
                }
                numberOfCrossLinks = noOfCrossLinks;
                hasArchBeenFound = true;
            }
            else // incorrect architecture:
            {
                // skip the cross link lines:
                for(int i = 0; i < noOfCrossLinks; i++)
                    fgets(line, buffer, filePointer);
            }

        }

    }

    fclose(filePointer);
    free(databaseFile);
    if(!hasArchBeenFound)
    {
        printf("Architecture %s was not found in the database!\n", architecture);
        exit(1);
    }
}

//Copies the header section of the data file; correctly substitutes the bond information
void CopyHeader(FILE* readFilePointer, FILE* writeFilePointer)
{
    //copying the first 4 lines as is:
    int buffer = 200;
    char line[buffer];
    for(int i = 0; i < 4; i++)
    {
        fgets(line, buffer, readFilePointer); // reading line
        fprintf(writeFilePointer, "%s", line); // writing line
    }

    // handling the bind information:
    //reading number of bonds:
    int bonds;
    fscanf(readFilePointer, "%i %*s\n", &bonds);
    bonds = bonds - 2 + 2 * numberOfCrossLinks; // updating the bonds: removing two bonds across polymers and adding the crosslinks
    fprintf(writeFilePointer, "%i bonds\n", bonds);
    //reading bond types:
    fgets(line, buffer, readFilePointer); // 2 bond types
    fprintf(writeFilePointer, "1 bond types\n");

    //copying all lines until the atoms section is reached:
    char word[6];
    while(true)
    {
        fgets(line, buffer, readFilePointer);
        fprintf(writeFilePointer, "%s", line); // writing the read line irrespective of what it contains

        //extracting first 5 chars from line to check if it is "Atoms":
        char word[6];
        strncpy(word, line, 5);
        word[5] = '\0'; //terminating character

        //checking if the word matches:
        if(strcmp(word, "Atoms") == 0)
        {
            // Atoms section reached and title printed
            break;
        }

    } 
    //Atoms section reached
}

//Handle the copying of the Atoms section
void CopyAtomsSection(FILE* readFilePointer, FILE* writeFilePointer)
{
    // the title has already been read and copied
    // copying all lines:
    char word[11]; // looking for the word "Velocities"
    int buffer = 200;
    char line[buffer];
    while(true)
    {
        fgets(line, buffer, readFilePointer);
        //looking for the word "Velocities" in the line:
        strncpy(word, line, 10);
        word[10] = '\0'; //terminating character
        if(strcasecmp(word, "Velocities") == 0)
            break;

        //else:
        fprintf(writeFilePointer, "%s", line);
    }
    // Velocities section reached
}

//Handle the copying of the Velocities section
void CopyVelocitiesSection(FILE* readFIlePointer, FILE* writeFilePoiner, bool skipSection)
{
    if(!skipSection)
        fprintf(writeFilePoiner, "Velocities\n"); // writing title of the section

    char word[6]; //looking for the word "Bonds"
    int buffer = 200;
    char line[buffer];
    while(true)
    {
        fgets(line, buffer, readFIlePointer);
        //extracting first 5 chars from line to check if it is "Bonds":
        char word[6];
        strncpy(word, line, 5);
        word[5] = '\0'; //terminating character
        if(strcasecmp(word, "Bonds") == 0)
        {
            //writing title for Bonds section:
            fprintf(writeFilePoiner, "%s", line);
            break;
        }
        //else
        if(!skipSection) // as long skipSection is not true
            fprintf(writeFilePoiner, "%s", line);
    }
}

//Handle the copying of the Bonds section:
void CopyBondsSection(FILE* readFilePointer, FILE* writeFilePointer)
{
    // reading till the end of file:
    int buffer = 200;
    char line[buffer];
    int bondCounter = 0; // counter to keep track of serial number of the bonds;

    while(true) 
    {
        fgets(line, buffer, readFilePointer);

        if(feof(readFilePointer) != 0) // feof returns 1 or some non zero value when EOF is reached; it is updated only after reading a line is tried when no new lines exist
            break;

        //checking if line is empty:
        if(line[0] == '\n')
        {
            fprintf(writeFilePointer, "%s", line);
            continue;
        }

        // line containing bond information:
        int bondType;
        int atom1, atom2; // the two bonded atoms' IDs for a particular bond
        sscanf(line, "%*i %i %i %i\n", &bondType, &atom1, &atom2);
        //debugging:
        // if(bondCounter == 399 || bondCounter == 400)
        //     printf("Bond Type = %i\n", bondType);
        
        if(bondType == 1)
            fprintf(writeFilePointer, "%i %i %i %i\n", ++bondCounter, bondType, atom1, atom2); // writing the line only if the bond type is 1

    }
    // reading the file finished
    //adding the extra cross link bonds for both rings:
    for(int i = 0; i < numberOfCrossLinks; i++)
    {
        fprintf(writeFilePointer, "%i %i %i %i\n", ++bondCounter, 1, crossLinks[i][0], crossLinks[i][1]); // for the 1st ring polymer
        fprintf(writeFilePointer, "%i %i %i %i\n", ++bondCounter, 1, crossLinks[i][0] + numberOfMonomers, crossLinks[i][1] + numberOfMonomers); // for the 2nd ring polymer
    }
    //done!
}


//Reads the mixed state file from the readFilePath and writes the new modified state file to the writeFilePath
void ReadAndWriteMixedState(const char* readFilePath, const char* writeFilePath, const bool skipVelocitiesSection)
{

    // opening files:
    FILE* readFilePointer; 
    if((readFilePointer = fopen(readFilePath, "r")) == NULL)
    {
        printf("Read File could not be found at %s!\n", readFilePath);
        exit(1);
    }
    FILE* writeFilePointer;
    if((writeFilePointer = fopen(writeFilePath, "w")) == NULL)
    {
        printf("Write File could not be opened at %s!\n", writeFilePath);
        exit(1);
    }

    // handling the header part of the file: before any major sections:
    CopyHeader(readFilePointer, writeFilePointer);
    // Atoms section:
    CopyAtomsSection(readFilePointer, writeFilePointer);
    //Velocities section:
    CopyVelocitiesSection(readFilePointer, writeFilePointer, skipVelocitiesSection);
    //Bonds Section:
    CopyBondsSection(readFilePointer, writeFilePointer);

    //closing file:
    fclose(readFilePointer);
    fclose(writeFilePointer);
}

//compares two strings and returns their difference: debugging
int CompareStrings(const char* string1, const char* string2)
{
    return strcmp(string1, string2);
}

//Reads the mixed state file and generates the initial state for a praticular run
void GenerateInitialState(int runNumber)
{
    char* readFilePath;
    char* writeFilePath;
    SetReadFilePath(&readFilePath, runNumber);
    SetWriteFilePath(&writeFilePath, runNumber);

    ReadAndWriteMixedState(readFilePath, writeFilePath, false);
    printf("Data file generated for %s run %i!\n", architecture, runNumber);   
}

int main(int argc, char** argv)
{
    // testing ReadCrossLinks:
    SetConstants(argc, argv);
    ReadCrosslinks();
    // printf("Number of Cross Links in %s : %i\n", architecture, numberOfCrossLinks);
    // printf("One example index: %i\n", crossLinks[numberOfCrossLinks - 1][1]);

    int numberOfRuns = 50;

    //checking if runNumber was provided as an argument:
    if(runNumber == -1) // runNumber was not provided; create states for all runs:
    {
        for(int runNumber = 1; runNumber <= numberOfRuns; runNumber++)
        {
            // int runNumber = 1;
            GenerateInitialState(runNumber);
        }
    }
    else
    {
        if(runNumber > numberOfRuns || runNumber < 1) // checking validity of runNumber
        {
            printf("Please enter a run number between 1 and %i! Run %i does not exist.\n", numberOfRuns, runNumber);
            exit(1);
        }
        else
        {
            GenerateInitialState(runNumber);
        }
    }
}
