// This is a header file that contains methods to read the position data of monomers from dump files generated by LAMMPS

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>

//Allocates memory for the positions array
double** AllocatePositionsArray(int totalMonomers)
{
    double** positions;
    // int totalMonomers = numberOfMonomers * numberOfPolymers;
    positions = (double**) malloc(totalMonomers * sizeof(double*));
    for(int n = 0; n < totalMonomers; n++)
        positions[n] = (double*) malloc(3 * sizeof(double)); //for the 3 coordinate directions
    
    return positions;
}

//Frees the memory allocated to the position array
void FreePositionsArray(double** positions, int totalMonomers)
{
    // int totalMonomers = numberOfMonomers * numberOfPolymers;
    for(int n = 0; n < totalMonomers; n++)
        free(positions[n]);
    free(positions);
}

//Sets the positions passed to the particular monomer in the positions array
void SetPositions(double** positions, int monomerIndex, double x, double y, double z)
{
    positions[monomerIndex - 1][0] = x;
    positions[monomerIndex - 1][1] = y;
    positions[monomerIndex - 1][2] = z;
}


//Reads the atomic positions from the position dump file for the next timeStep. 
//Returns true if the time step is less than the max and the positions was successfully read, otherwise returns false. If successfully read, it updates the timeStep pointer
bool ReadNextTimeStepsPositions(FILE* readFilePointer, double** positions, int* timeStepPointer, const int maximumTimeStep, const int totalMonomers)
{
    int buffer = 200;
    char line[buffer];

    const int headerLength = 9; // the number of lines for every timestep in the dump file that before the position data
    //debugging:
    // printf("Before reading the first line of the header\n");
    // skipping the header lines, after extracting the time step from the second line in the header:
    fgets(line, buffer, readFilePointer); // skipping the first line of the header
    //debugging:
    // printf("First line of the header: %s", line);

    //Checking if end of file has been reached:
    if(feof(readFilePointer) != 0)
    {
        printf("End of File of the Positions Dump file reached!\n");
        return false;
    }

    //debugging:
    // printf("Before reading timestep: Ftell = %ld\n", ftell(readFilePointer));

    //Reading the time step in the second line. The return character is important for the next line to be skipped effectively
    fscanf(readFilePointer, "%i\n", timeStepPointer); // The timeStep should get updated here for later use
    //debugging:
    // printf("After reading timestep: Ftell = %ld\n", ftell(readFilePointer));
    // using fgets to progress the file pointer to move along the file. fscanf does not seem to be moving the pointer
    // fgets(line, buffer, readFilePointer);
    // printf("Line stored in progressed line: %s", line);
    //debugging:
    // printf("After reading timestep and progressing: Ftell = %ld\n", ftell(readFilePointer));
    
    //debugging:
    // printf("Timestep was read as %i\n", timeStep);

    //checking if the timeStep is below the maximumTimeStep limit:
    int timeStep = *timeStepPointer;
    if(timeStep > maximumTimeStep)
    {
        printf("Maximum Time Step reached!\n");
        return false;
    }

    // Skipping the rest of the lines: header without the first two lines
    for(int i = 0; i < headerLength - 2; i++)
    {
        fgets(line, buffer, readFilePointer);
    }

    //debugging:
    // printf("After header has been skipped. Line: %s ftell = %ld\n", line, ftell(readFilePointer));

    // now starting to parse the position data:
    // printf("Number of position entries: %i\n", numberOfPositionEntries);
    for(int i = 0; i < totalMonomers; i++)
    {
        int atomID, atomType;
        double x, y, z;
        //Scanning the atom position data using fscanf: Here too, needs to be specified to terminate the line effectively
        fscanf(readFilePointer, "%i %i %lf %lf %lf\n", &atomID, &atomType, &x, &y, &z);
        SetPositions(positions, atomID, x, y, z);

        //debugging: checking if the the atomID is being read properly
        if(atomID < 1 || atomID > totalMonomers)
            printf("Atom ID seems to be incorrectly read while reading positions dump file. TimeStep = %i, AtomID = %i, (x, y, z) = (%lf, %lf, %lf)\n", timeStep, atomID, x, y, z);
    }
    //debugging:
    // printf("After positions are read. Line: %s ftell = %ld\n", line, ftell(readFilePointer));

    //Everything worked perfectly: returning true
    return true;
    //debugging:
    // printf("Last line read in the atoms section: %s\n", line);
}

//Calculates the distance between two position vectors
double CalculateDistance(double position1[3], double position2[3])
{
    double distance = 0;
    for(int i = 0; i < 3; i++)
    {
        distance += pow(position1[i] - position2[i], 2);
    }
    distance = sqrt(distance);
    return distance;
}

// Creates and returns a file pointer for the opened file
FILE* GetFilePointer(char* filePath, char* fileMode)
{
    FILE* filePointer;
    if((filePointer = fopen(filePath, fileMode)) == NULL)
    {
        printf("The file %s could not be opened!\n", filePath);
        exit(1);
    }
    return filePointer;
}