// This is a script to read the mixed state dump files generated by the fixing bonding method 
// and copy and edit it to make it a valid data file for running segregation of a particular architecture.

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>

#define LINES_LIMIT 100*numberOfMonomers

#include "../../Global_Scripts/System_File_Paths/system_file_paths.h"
#include GENERAL_FILE_METHODS
#include CROSS_LINKS_DATABASE
#include STATE_CONFIG
#include MODULO

// global variables:
char* mixed_file_directory; // The directory where the mixed state file resides
char* destination_directory; // The directory where the mixed state file needs to be copied
char* architecture; // The architecture of which the mixed state is generated
char* requiredArchitecture; // The architecture that the user wants to use the mixed state for. May not be same as the architecture for which the mixed state was generated
int numberOfMonomers;
int numberOfPolymers = 2;
int totalMonomers;
int runNumber;
char* atomStyle[20]; // The LAMMPS atom style being used in the simulation. For example: "bond", "angle", etc
bool writeIndividualPolymerStates = false; // A flag that indicates whether both polymers should be written to separate files as individual polymers in the system
// If they are written to individual files, then they are meant to be simulated separately 
char* initializationProcedure; // The name of the procedure used to generate the mixed state; for example: "fene_recenter", "fene_glued", etc. This is used to set the path for the mixed state file to be read from
bool deleteBackbone = false; // A flag to indicate whether the backbones in both polymers should be deleted so that only the side loops remain in the system
// This is useful if one wants to check for internal concatenations, or concatenations between different side loops of the same polymer.
// The deletion is done based on the cross links read from the database file. Note that this only works for architectures with side loops.
// Currently, the deletion will only work if the polymers are written separately
bool doInterPolymerBondsExist = DO_INTERPOLYMER_BONDS_EXIST;
bool doGhostAtomsExist = DO_GHOST_ATOMS_EXIST; // A flag to indicate whether the ghost atoms and their bonds in the shrink-relax + fixing-bonding algorithm exist in the mixed states
bool keepTerCrossLink = KEEP_TER_CROSSLINK; // A flag to indicate whether the ter cross link should be kept in the resultant mixed state. 
// These must be set manually in the state_config.h file
// The ter cross link is the bond between the two terminal "ends" of the ring polymers. 
// In exact terms, it is the bond between the monomers located at the halfway point around the ring in either polymer.

int currentIndexOfPolymer;

Architecture archCrossLinks; // The architecture struct to store the crosslinks for the architecture

bool transFormArchitecture = false; // a flag to indicate whether the architecture for which the mixed state is generated is different from the ddestination/required architecture
// Transforming the architecture might be useful when going from an architecture with more cross links to an architecture with lower cross links
// such that the cross links in the new architecture is a subset of the cross links of the old architecture.
// This will ensure that no new cross links are introduced between distant monomers in the new run.
// Someone might want to do this to reuse the mixed state of a higher architecture for a lower one.

// Set the below flags' values manually in the state_config.h file:
bool doesVelocitySectionExist = VELOCITY_SECTION_EXISTS; // a flag to indicate whether the mixed state file being read from has a velocity section or not; set this manually
bool doesMassesSectionExist = MASS_SECTION_EXISTS; // a flag to indicate whether the mixed state file being read from has a masses section or not; set this manually
bool doAtomFlagsExist = ATOM_FLAGS_EXIST; // a flag to indicate whether the atom style used has printed the PBC flags for each atom
bool useDifferentBondTypeForCrossLinks = USE_DIFF_BOND_TYPE;
bool useCrossLinksForRegions = USE_CROSSLINK_REGIONS; // a flag to indicate whether the cross linked atoms should be used as ranges for the different regions; see below

// dividing the architecture into different regions for visualizing as different parts of the polymer: must be set manually
// Architecture: Arc1_10
int numberOfRegions = 0; // regions apart from the polymer backbone
// int regions[4][2] = {{1, 50}, {151, 200}, {63, 87}, {113, 137}}; // array of pairs: {lower index, upper index}: Arc2-2
int regions[1][2] = {{1, 200}};
// OR:
// if useCrossLinksForRegions is true, then the corss link atoms will be used as the end points of the regions
// TODO: match these regions for the side loops; so that the different side loops can be differently coloured

// Sets the values of the global constant variables based on the arguments passed
void SetConstants(int argc, char** argv)
{
    int numberOfMandatoryArguments = 5;
    if(argc < numberOfMandatoryArguments + 1) // number of arguments passed is less than expected
    {
        printf("Not enough arguments passed! Please pass the number of monomers(int), the architecture(string), the flag indicating if the polymer backbone should be deleted (0 or 1), the name of the initialization procedure, and the filepath to the directory where the state is to be copied (string) as arguments from the command line\n");
        printf("For example:\n./createInitialStateExecuatable.out 200 Arc2 0 fene_recenter /scratch/Harsh/New_Segregation/\n");
        printf("Optional arguments for another architecture (to which the state should be converted to) and the particular run number can also be passed after the mandatory arguments if desired\n");
        exit(1);
    }
    else
    {
        //assuming atleast two arguments were passed; apart from the default program name
        architecture = argv[2]; // the second argument after the program name
        numberOfMonomers = atoi(argv[1]); // the first argument after the program name
        //atoi(char*) is a function that takes an argument and returns the int expressed as the character string. If the characters are not a number, it returns 0
        if(numberOfMonomers == 0)
        {
            printf("First argument \"%s\" passed was not a valid value for number of monomers! Please pass a valid integer\n", argv[2]);
            exit(1);
        }
        // reading the flag:
        if(argv[3][0] == '0')
        {
            deleteBackbone = false;
        }
        else
        {
            writeIndividualPolymerStates = true; // We delete backbone to check for internal concatenations within a polymer;
            // Thus, we take the case of each polymer separately
            deleteBackbone = true;
        }
        totalMonomers = numberOfMonomers * numberOfPolymers;
        initializationProcedure = argv[4];
        destination_directory = argv[5];
    }

    char* createDirectory;
    SetAbsolutePath(&createDirectory, CREATE_INITIAL_STATES);
    SetDirectoryPath(&mixed_file_directory, createDirectory, numberOfMonomers, initializationProcedure);
    free(createDirectory);
    SetDirectoryPath(&destination_directory, destination_directory, numberOfMonomers, initializationProcedure);
    
    // getting optional arguments:
    // default value for optional destination architecture:
    requiredArchitecture = (char*) malloc(10 * sizeof(char));
    strcpy(requiredArchitecture, architecture);
    runNumber = GetOptionalArguments(&requiredArchitecture, argc, argv, numberOfMandatoryArguments);

    if(strcmp(architecture, requiredArchitecture) == 0) 
    {
        transFormArchitecture = false;
    }
    else
    {
        transFormArchitecture = true;
        printf("Warning: You are attempting to transform the mixed state file of %s to one of %s.", architecture, requiredArchitecture);
        printf("If there are any new crosslinks introduced, then the subsequent simulations might show chain crossing.\n");
    }
}

//Sets the file name of the mixed state dump with the passed runNumber at the specified string pointer
void SetMixedStateFileName(char** fileNamePointer, int runNumber)
{   
    int bytes = 0;
    // char* prefix = "langevin_";
    char* prefix = "langevin_";
    bytes = asprintf(fileNamePointer, "/%smixed_state_%.2i.txt", prefix, runNumber);
    
    if(bytes == -1)
    {
        printf("Memory could not be allocated for the Mixed State File Name!\n");
        exit(1);
    }
}

//Sets the read file path in the mixed state directory
void SetReadFilePath(char** filePathPointer, int runNumber)
{
    char* fileName;
    SetMixedStateFileName(&fileName, runNumber);
    Append(filePathPointer, mixed_file_directory, architecture, fileName);
}

void SetWriteFileName(char** fileNamePointer)
{
    int bytes = asprintf(fileNamePointer, "initial_configuration%i.txt", currentIndexOfPolymer);
    if(bytes == -1)
    {
        printf("Memory could not be allocated for the separated initial configuration file name!\n");
        exit(1);
    }
}

//Sets the write file path in the destination directory
void SetWriteFilePath(char** filePathPointer, int runNumber)
{
    char* folderName;
    char* fileName;
    if(writeIndividualPolymerStates)
        SetWriteFileName(&fileName);
    else
        fileName = "initial_configuration.txt";

    SetFolderName(&folderName, requiredArchitecture, runNumber);
    Append(filePathPointer, destination_directory, folderName, fileName);
    if(writeIndividualPolymerStates)
        free(fileName);
}

// Checks whether an atom ID query lies between the specfied ID limits
bool IsInRange(int query, int lowerLimit, int upperLimit)
{
    if(upperLimit >= lowerLimit) // The usual case
    {
        if(query >= lowerLimit && query <= upperLimit)
            return true;
        else
            return false;
    }
    else // when upper limit < lower limit; i.e the range spans across the oriC discontinuity
    {
        // The query is in the region only if the query is greater than the lower limit or lower than the upper limit
        // Both can't be met simulataneously for this case
        if(query >= lowerLimit || query <= upperLimit)
            return true;
        else
            return false;
    }
}

// Returns the atomID of the atom belonging to the first polymer corresponding to the atom passed
int GetReducedAtomID(int atomID)
{
    return (atomID-1) % numberOfMonomers + 1; // For example: return value lies between 1 and 200
}

// Determines whether the passed atomID belongs to one of the side loops or not based on the architecture cross links
bool DoesAtomBelongToSideLoops(int atomID)
{
    // reducing the atomID to the corresponding atomID of the first polymer:
    atomID = GetReducedAtomID(atomID); // lies between 1 and numberOfMonomers
    
    // Checking if the atom lies on any of the side loops according to the cross links:
    for(int i = 0; i < archCrossLinks.numberOfCrossLinks; i++)
    {
        if(IsInRange(atomID, archCrossLinks.crossLinks[i][0], archCrossLinks.crossLinks[i][1]))
        {
            return true;
        }
    }
    //else: lies in none of the side loops
    return false;
}

// Determines whether the particular bond passed belongs to one of the side loops or not based on the architecture cross links
bool DoesBondBelongToSideLoops(int bondAtomID1, int bondAtomID2)
{
    // reducing both atom IDs:
    bondAtomID1 = GetReducedAtomID(bondAtomID1);
    bondAtomID2 = GetReducedAtomID(bondAtomID2);

    // The bond belongs to a side loop if and only if both bond atoms belong to the same side loop.
    // Checking if both atoms belong to the same side loop:
    for(int i = 0; i < archCrossLinks.numberOfCrossLinks; i++)
    {
        if(IsInRange(bondAtomID1, archCrossLinks.crossLinks[i][0], archCrossLinks.crossLinks[i][1]) && IsInRange(bondAtomID2, archCrossLinks.crossLinks[i][0], archCrossLinks.crossLinks[i][1]))
            return true;
    }
    //else: Bond does not belong to any side loop
    return false;
}

// Determines whether the particular bond passed is the ter cross link
bool IsBondTerCrossLink(int bondAtomID1, int bondAtomID2)
{
    bondAtomID1 = GetReducedAtomID(bondAtomID1);
    bondAtomID2 = GetReducedAtomID(bondAtomID2); // Reducing both IDs to the corresponding one in the 1st polymer
    if((bondAtomID1 == numberOfMonomers/2) && (bondAtomID2 == numberOfMonomers/2)) // both the bond atoms are one end of the ring polymer
        return true;
    else
        return false;
}

// Returns the number of atoms/bonds present in all of the side loops combined
int CalculateSideLoopsAtoms(void)
{
    int numberOfSideLoopAtoms = 0; // This is numerically equal to the number of bonds present in the side loops
    for(int i = 0; i < archCrossLinks.numberOfCrossLinks; i++)
    {
        numberOfSideLoopAtoms += modulo(archCrossLinks.crossLinks[i][1] - archCrossLinks.crossLinks[i][0], numberOfMonomers) + 1; 
        // both ends included; assuming all side loops form disjoint sets of atoms.
        // The modulo takes care of the case when upperCrossLink < lowerCrossLink
        // Assuming the cross link bond atoms are ordered properly
    }
    return numberOfSideLoopAtoms;
}

// Returns the number of ghost atoms present in the system
int GetGhostAtoms(int numberOfPolymers)
{
    int ghostAtomsPerPolymer;
    if(archCrossLinks.isArcLinear)
        ghostAtomsPerPolymer = 1;
    else
        ghostAtomsPerPolymer = 2;
    return ghostAtomsPerPolymer * numberOfPolymers;
}

// Copies lines from the readFile to the writeFile till the query word is reached
void CopyLinesTillQuery(FILE* readFilePointer, FILE* writeFilePointer, char* query, bool doNotWrite)
{
    int wordLength = strlen(query);
    char word[wordLength + 1]; // looking for the word that matches the query
    int buffer = 200;
    char line[buffer];
    
    int lineCounter = 0; // A counter to count the number of lines copied

    while(true)
    {
        fgets(line, buffer, readFilePointer);
        lineCounter++;
        //looking for the query word in the line:
        strncpy(word, line, wordLength);
        word[wordLength] = '\0'; //terminating character
        if(strcasecmp(word, query) == 0)
            break; // does not copy the line where the query is found

        //else:
        if(!doNotWrite)
            fprintf(writeFilePointer, "%s", line); // writes the read line only if doNotWrite is false
        
        // Checking if the copied lines have exceeded the limit:
        if(lineCounter > LINES_LIMIT)
        {
            printf("The number of lines read/copied exceeded the set limit before the query %s was found! terminating.\n", query);
            exit(1);
        }
    }
    // writing the atoms title; since the the atoms section will definitely be printed
    if(strcmp(query, "Atoms") == 0)
        fprintf(writeFilePointer, "%s", line); // writing the last line that was read; i.e. the title
}

//Copies the header section of the data file; correctly substitutes the bond information
void CopyHeader(FILE* readFilePointer, FILE* writeFilePointer)
{
    //copying the first 2 lines as is:
    int buffer = 200;
    char line[buffer];
    for(int i = 0; i < 2; i++)
    {
        fgets(line, buffer, readFilePointer); // reading line
        fprintf(writeFilePointer, "%s", line); // writing line
    }

    // handling the atom information:
    int numberOfAtomTypes;
    fgets(line, buffer, readFilePointer); // atoms line
    fgets(line, buffer, readFilePointer); // atom types line
    sscanf(line, "%i atom types\n", &numberOfAtomTypes); // recording the number of atom types, even  if it may be greater than the number of polymers

    fprintf(writeFilePointer, "%i atoms\n%i atom types\n", totalMonomers, numberOfPolymers);

    // handling the bond information:
    // Computing ideal number of bonds:
    int bonds = 2 * (numberOfMonomers + archCrossLinks.numberOfCrossLinks);
    fgets(line, buffer, readFilePointer); // skipping number of bonds line
    // Removing bond between first and last monomer for Arc_Lin
    if(archCrossLinks.isArcLinear)
        bonds -= numberOfPolymers; // 1 bond for each polymer removed
    // Adding the ter cross link if required
    if(keepTerCrossLink && doInterPolymerBondsExist)
        bonds += 1;

    fprintf(writeFilePointer, "%i bonds\n", bonds);
    //reading bond types:
    fgets(line, buffer, readFilePointer); // 2 bond types
    int numberOfBondTypes = 1;
    if(keepTerCrossLink)
        numberOfBondTypes = 2;
    if(useDifferentBondTypeForCrossLinks)
        numberOfBondTypes = 3;
    fprintf(writeFilePointer, "%i bond types\n", numberOfBondTypes);

    // copying the box dimensions and the blank lines before and after it: 5 lines
    for(int i = 0; i < 5; i++)
    {
        fgets(line, buffer, readFilePointer); // reading line
        fprintf(writeFilePointer, "%s", line); // writing line 
    }
    // Mass Section reached if it exists
    
    if(doesMassesSectionExist)
    {
        // copying the first two lines including the title:
        for(int i = 0; i < 2; i++)
        {
            fgets(line, buffer, readFilePointer); // reading line
            fprintf(writeFilePointer, "%s", line); // writing line
        }

        // copying masses:
        for(int i = 0; i < numberOfAtomTypes; i++)
        {
            int atomType, mass;
            fgets(line, buffer, readFilePointer); // reading line
            sscanf(line, "%i %i\n", &atomType, &mass);
            if(atomType > numberOfPolymers) // the atom type is that of extra atoms that will be removed
                continue;
            fprintf(writeFilePointer, "%s", line); // writing line
        }
    }

    //copying the rest of the lines until the atoms section is reached:
    char* query = "Atoms";
    CopyLinesTillQuery(readFilePointer, writeFilePointer, query, false);
    //Atoms section reached; title printed
}

//Handle the copying of the header for both individual polymer files:
void CopyHeaderSectionSeparately(FILE* readFilePointer, FILE* writeFilePointer1, FILE* writeFilePointer2)
{
    //copying the first 2 lines as is:
    int buffer = 200;
    char line[buffer];
    for(int i = 0; i < 2; i++)
    {
        fgets(line, buffer, readFilePointer); // reading line
        fprintf(writeFilePointer1, "%s", line); // writing line
        fprintf(writeFilePointer2, "%s", line); // writing line
    }

    //modifying the atom and bonds information:
    int numberOfAtoms = numberOfMonomers;
    int numberOfBonds = numberOfMonomers + archCrossLinks.numberOfCrossLinks;
    if(archCrossLinks.isArcLinear)
        numberOfBonds -= 1; // Removing the bond between the the last and first monomers

    if(deleteBackbone)
    {
        numberOfAtoms = CalculateSideLoopsAtoms();
        numberOfBonds = numberOfAtoms;
        if(numberOfAtoms == 0) // No side loops present in the architecture
        {
            printf("This architecture does not have any side loops, and thus, deleting the backbone would leave no atoms. Terminating.\n");
            exit(1);
        }
    }

    int numberOfBondTypes = 1;
    if(useDifferentBondTypeForCrossLinks)
        numberOfBondTypes = 3;
    
    int numberOfAtomTypes;
    if(useCrossLinksForRegions)
        numberOfAtomTypes = archCrossLinks.numberOfCrossLinks + 1;
    else
        numberOfAtomTypes = numberOfRegions + 1;
    fprintf(writeFilePointer1, "%i atoms\n%i atom types\n", numberOfAtoms, numberOfAtomTypes);
    fprintf(writeFilePointer1, "%i bonds\n1 bond types\n", numberOfBonds);
    fprintf(writeFilePointer2, "%i atoms\n%i atom types\n", numberOfAtoms, numberOfAtomTypes);
    fprintf(writeFilePointer2, "%i bonds\n%i bond types\n", numberOfBonds, numberOfBondTypes);

    //skipping bonds and atoms information in the read file:
    for(int i = 0; i < 4; i++)
        fgets(line, buffer, readFilePointer);

    if(doesMassesSectionExist)
    {
        //copying all lines until the masses section is reached:
        char* query = "Masses";
        long filePosition = ftell(readFilePointer);
        // For writeFile1:
        CopyLinesTillQuery(readFilePointer, writeFilePointer1, query, false);
        // Restoring position and copying for writeFile2:
        fseek(readFilePointer, filePosition, SEEK_SET); // going to filePosition from the start (SEEK_SET) of the file
        CopyLinesTillQuery(readFilePointer, writeFilePointer2, query, false);
        //Masses section reached
        fprintf(writeFilePointer1, "Masses \n\n");
        fprintf(writeFilePointer2, "Masses \n\n");
        //Printing masses:
        for(int i = 1 ; i <= numberOfAtomTypes; i++)
        {
            fprintf(writeFilePointer1, "%i 1\n", i);
            fprintf(writeFilePointer2, "%i 1\n", i);
        }
        // Printing empty lines:
        fprintf(writeFilePointer1, "\n");
        fprintf(writeFilePointer2, "\n");
    }

    //Skipping in read file till atoms section is reached:
    char* query = "Atoms";
    long filePosition = ftell(readFilePointer);
    CopyLinesTillQuery(readFilePointer, writeFilePointer1, query, doesMassesSectionExist); // Not copying to the write file if Masses section exists
    fseek(readFilePointer, filePosition, SEEK_SET); // going to filePosition from the start (SEEK_SET) of the file
    CopyLinesTillQuery(readFilePointer, writeFilePointer2, query, doesMassesSectionExist);
    //Atoms section reached; Atoms title printed
    //Printing an empty line:
    // fprintf(writeFilePointer1, "\n");
    // fprintf(writeFilePointer2, "\n");
}

//Handle the copying of the Atoms section
void CopyAtomsSection(FILE* readFilePointer, FILE* writeFilePointer)
{
    int buffer = 200;
    char line[buffer];
    // Assuming the title has been printed
    fgets(line, buffer, readFilePointer); // blank line
    fprintf(writeFilePointer, "\n"); // writing a blank line

    int numberOfAtoms = totalMonomers;
    if(doGhostAtomsExist)
        numberOfAtoms += GetGhostAtoms(numberOfPolymers);
    for(int i = 0; i < numberOfAtoms; i++)
    {
        int atomID, molID, atomType;
        double x, y, z;
        int flag_x, flag_y, flag_z;
        //reading the line:
        fgets(line, buffer, readFilePointer);
        int items = sscanf(line, "%i %i %i %lf %lf %lf %i %i %i\n", &atomID, &molID, &atomType, &x, &y, &z, &flag_x, &flag_y, &flag_z);

        //skipping ghost atoms:
        if(atomType > numberOfPolymers)
            continue;
        
        // writing the atom line as is:
        fprintf(writeFilePointer, "%i %i %i %lf %lf %lf", atomID, molID, atomType, x, y, z);
            if(doAtomFlagsExist)
                fprintf(writeFilePointer, " %i %i %i", flag_x, flag_y, flag_z); // printing flags if they exist
            fprintf(writeFilePointer, "\n"); // printing the return character after the line
    }
    
    // copying the rest of the lines before the next section:
    char* query = "Bonds";
    if(doesVelocitySectionExist)
        query = "Velocities";
    CopyLinesTillQuery(readFilePointer, writeFilePointer, query, false);

    // Velocities/Bonds Section section reached; title not printed
}

// Returns the atom type for the given atom ID according to the cross links' regions
int GetAtomTypeFromCrossLinks(int reducedAtomID)
{
    // Assuming the atomId is reduced
    for(int i = 0; i < archCrossLinks.numberOfCrossLinks; i++)
    {
        if(IsInRange(reducedAtomID, archCrossLinks.crossLinks[i][0], archCrossLinks.crossLinks[i][1]))
            return i+2;
    }
    //else:
    return 1; //default type
}

// Returns the atom type for the given atom ID according to the regions set manually
int GetAtomTypeFromRegions(int reducedAtomID)
{
    // Assuming the atomID is reduced
    for(int i = 0; i < numberOfRegions; i++)
    {
        if(IsInRange(reducedAtomID, regions[i][0], regions[i][1]))
            return i+2;
    }
    //else:
    return 1; //default type
}

//Returns the atom type for the given atom ID according to the regions of the polymer
int GetAtomType(int atomID)
{
    atomID = GetReducedAtomID(atomID); // Reducing the atomID
    if(useCrossLinksForRegions)
        return GetAtomTypeFromCrossLinks(atomID);
    else
        return GetAtomTypeFromRegions(atomID);
}

//Handling the copying of the atoms section for both individual polymer files
void CopyAtomsSectionSeparately(FILE* readFilePointer, FILE* writeFilePointer1, FILE* writeFilePointer2)
{
    // Assuming the Atoms title has been printed
    // writing the blank line as it is
    int buffer = 200;
    char line[buffer];
    fgets(line, buffer, readFilePointer);
    fprintf(writeFilePointer1, "%s", line);
    fprintf(writeFilePointer2, "%s", line);

    // iterating over all atom positions:
    int numberOfAtoms = totalMonomers;
    if(doGhostAtomsExist)
        numberOfAtoms += GetGhostAtoms(numberOfPolymers);
    for(int i = 0; i < numberOfAtoms; i++)
    {
        int atomID, molID, atomType;
        double x, y, z;
        int flag_x, flag_y, flag_z;
        //reading the line:
        fgets(line, buffer, readFilePointer);
        int items = sscanf(line, "%i %i %i %lf %lf %lf %i %i %i\n", &atomID, &molID, &atomType, &x, &y, &z, &flag_x, &flag_y, &flag_z);

        // skipping ghost atoms:
        if(atomType > numberOfPolymers)
            continue;

        atomType = GetAtomType(atomID);
        
        // Checking if the atom is in the backbone and needs to be deleted:
        if(deleteBackbone && !DoesAtomBelongToSideLoops(atomID))
        {
            continue; // continuing without printing this line
        }

        if(atomID <= numberOfMonomers) // first polymer
        {
            fprintf(writeFilePointer1, "%i %i %i %lf %lf %lf", atomID, molID, atomType, x, y, z);
            if(doAtomFlagsExist)
                fprintf(writeFilePointer1, " %i %i %i", flag_x, flag_y, flag_z); // printing flags if they exist
            fprintf(writeFilePointer1, "\n"); // printing the return character after the line
        }
        else // second polymer
        {
            atomID = atomID - numberOfMonomers;
            fprintf(writeFilePointer2, "%i %i %i %lf %lf %lf", atomID, molID, atomType, x, y, z);
            if(doAtomFlagsExist)
                fprintf(writeFilePointer2, " %i %i %i", flag_x, flag_y, flag_z); // printing flags if they exist
            fprintf(writeFilePointer2, "\n"); // printing the return character after the line
        }
    }

    //printing the next lines as is:
    fgets(line, buffer, readFilePointer);
    fprintf(writeFilePointer1, "%s", line);
    fprintf(writeFilePointer2, "%s", line);
    //Velocities section reached; title not printed
}

//Handle the copying of the Velocities section
void CopyVelocitiesSection(FILE* readFilePointer, FILE* writeFilePointer, bool skipSection)
{
    // Printing the title:
    fprintf(writeFilePointer, "Velocities\n");
    // writing the first line as is
    int buffer = 200;
    char line[buffer];

    fgets(line, buffer, readFilePointer);
    fprintf(writeFilePointer, "%s", line);

    //iterating over all the atoms:
    int numberOfAtoms = totalMonomers;
    if(doGhostAtomsExist)
        numberOfAtoms += GetGhostAtoms(numberOfPolymers);
    for(int i = 0; i < numberOfAtoms; i++)
    {
        int atomID;
        double x, y, z; //velocities
        fgets(line, buffer, readFilePointer);
        int items = sscanf(line, "%i %lf %lf %lf\n", &atomID, &x, &y, &z);
        
        // skipping the ghost atoms:
        if(atomID > totalMonomers)
            continue;

        fprintf(writeFilePointer, "%i %lf %lf %lf\n", atomID, x, y, z);
    }
    
    // copying the rest of the lines:
    char* query = "Bonds";
    CopyLinesTillQuery(readFilePointer, writeFilePointer, query, skipSection);
    // Bonds section reached, title not written
}


//Handle copying of the velocities section for both individual polymer files
void CopyVelocitiesSectionSeparately(FILE* readFilePointer, FILE* writeFilePointer1, FILE* writeFilePointer2, bool skipSection)
{
    // writing the first two lines as is; should include the title
    int buffer = 200;
    char line[buffer];

    for(int i = 0; i < 2; i++)
    {
        fgets(line, buffer, readFilePointer);
        fprintf(writeFilePointer1, "%s", line);
        fprintf(writeFilePointer2, "%s", line);
    }

    //iterating over all the atoms:
    int numberOfAtoms = totalMonomers;
    if(doGhostAtomsExist)
        numberOfAtoms += GetGhostAtoms(numberOfPolymers);
    for(int i = 0; i < numberOfAtoms; i++)
    {
        int atomID;
        double x, y, z; //velocities
        fgets(line, buffer, readFilePointer);
        int items = sscanf(line, "%i %lf %lf %lf\n", &atomID, &x, &y, &z);
        
        // skipping the ghost atoms:
        if(atomID > totalMonomers)
            continue;
        // Checking if the atom is in the backbone and needs to be deleted:
        if(deleteBackbone && !DoesAtomBelongToSideLoops(atomID))
        {
            continue; // continuing without printing this line
        }

        if(atomID <= numberOfMonomers) // first polymer
        {
            fprintf(writeFilePointer1, "%i %lf %lf %lf\n", atomID, x, y, z);
        }
        else //second polymer
        {
            atomID = atomID - numberOfMonomers;
            fprintf(writeFilePointer2, "%i %lf %lf %lf\n", atomID, x, y, z);
        }
    }

    // reading the next line as it is
    for(int i = 0; i < 1; i++)
    {
        fgets(line, buffer, readFilePointer);
        fprintf(writeFilePointer1, "%s", line);
        fprintf(writeFilePointer2, "%s", line);
    }
    // Skipping the bonds title:
    fgets(line, buffer, readFilePointer);
    //Bonds section reached; Title not printed
}

//Handle the copying of the Bonds section:
void CopyBondsSection(FILE* readFilePointer, FILE* writeFilePointer)
{
    // Printing the title:
    fprintf(writeFilePointer, "Bonds\n");
    // reading till the end of file:
    int buffer = 200;
    char line[buffer];
    int bondCounter = 0; // counter to keep track of serial number of the bonds;

    while(true) 
    {
        fgets(line, buffer, readFilePointer);

        if(feof(readFilePointer) != 0) // feof returns 1 or some non zero value when EOF is reached; it is updated only after reading a line is tried when no new lines exist
            break;

        //checking if line is empty:
        if(line[0] == '\n')
        {
            fprintf(writeFilePointer, "%s", line);
            continue;
        }

        // line containing bond information:
        int bondType;
        int atom1, atom2; // the two bonded atoms' IDs for a particular bond
        sscanf(line, "%*i %i %i %i\n", &bondType, &atom1, &atom2);
        //debugging:
        // if(bondCounter == 399 || bondCounter == 400)
        //     printf("Bond Type = %i\n", bondType);
        
        if(bondType == 1 || (keepTerCrossLink && doInterPolymerBondsExist && IsBondTerCrossLink(atom1, atom2)))
            fprintf(writeFilePointer, "%i %i %i %i\n", ++bondCounter, bondType, atom1, atom2); // writing the line only if the bond type is not 2; or if it is the ter cross link

    }
}

void GenerateBondsSectionSeparately(FILE* writeFilePointer)
{
    // Printing the title:
    fprintf(writeFilePointer, "Bonds\n");
    //printing a blank line:
    fprintf(writeFilePointer, "\n");

    //printing bond information for Arc0 bonds:
    int bondID = 1; // a counter to keep track of the bond ID
    int bondType = 1;
    for(int i = 1; i < numberOfMonomers; i++)
    {
        int atom1ID = i;
        int atom2ID = i + 1;
        // Checking if the bond is part of the backbone and needs to be deleted:
        if(deleteBackbone && !DoesBondBelongToSideLoops(atom1ID, atom2ID))
            continue; // continuing without printing

        fprintf(writeFilePointer, "%i %i %i %i\n", bondID++, bondType, atom1ID, atom2ID);
    }
    //printing the last bond separately: only if it is not part of the backbone and is not linear
    if(!(deleteBackbone && !DoesBondBelongToSideLoops(numberOfMonomers, 1)) && !archCrossLinks.isArcLinear)
        fprintf(writeFilePointer, "%i %i %i %i\n", bondID++, bondType, numberOfMonomers, 1);
    
    // printing the cross links for the required architecture: All cross links are part of the side loops by default
    if(useDifferentBondTypeForCrossLinks)
        bondType = 3;
    for(int i = 0; i < archCrossLinks.numberOfCrossLinks; i++)
    {
        fprintf(writeFilePointer, "%i %i %i %i\n", bondID++, bondType, archCrossLinks.crossLinks[i][0], archCrossLinks.crossLinks[i][1]); // for the 1st ring polymer
    }
}

//Generate Bonds section instead of copying the one in the read file
void GenerateBondsSection(FILE* writeFilePointer)
{
    // Prinitng the title:
    fprintf(writeFilePointer, "Bonds\n");

    //printing a blank line:
    fprintf(writeFilePointer, "\n");

    //printing bond information for Arc0 bonds:
    int bondID = 1; // a counter to keep track of the bond ID
    int bondType = 1;
    for(int n = 0; n < 2; n++) // iterating over number of polymers
    {
        for(int i = 1; i < numberOfMonomers; i++)
        {
            int atom1ID = n * numberOfMonomers + i;
            int atom2ID = n * numberOfMonomers + i + 1;
            fprintf(writeFilePointer, "%i %i %i %i\n", bondID++, bondType, atom1ID, atom2ID);
        }
        //printing the last bond separately if architecture isn't linear:
        if(!archCrossLinks.isArcLinear)
            fprintf(writeFilePointer, "%i %i %i %i\n", bondID++, bondType, (n+1) * numberOfMonomers, n * numberOfMonomers + 1);
    }
    
    // printing the cross links for the required architecture:
    if(useDifferentBondTypeForCrossLinks)
        bondType = 3;
    for(int i = 0; i < archCrossLinks.numberOfCrossLinks; i++)
    {
        fprintf(writeFilePointer, "%i %i %i %i\n", bondID++, bondType, archCrossLinks.crossLinks[i][0], archCrossLinks.crossLinks[i][1]); // for the 1st ring polymer
        fprintf(writeFilePointer, "%i %i %i %i\n", bondID++, bondType, archCrossLinks.crossLinks[i][0] + numberOfMonomers, archCrossLinks.crossLinks[i][1] + numberOfMonomers); // for the 2nd ring polymer
    }

}


//Reads the mixed state file from the readFilePath and writes the new modified state file to the writeFilePath
void ReadAndWriteMixedState(const char* readFilePath, const char* writeFilePath, const bool skipVelocitiesSection)
{
    // opening files:
    FILE* readFilePointer; 
    if((readFilePointer = fopen(readFilePath, "r")) == NULL)
    {
        printf("Read File could not be found at %s!\n", readFilePath);
        exit(1);
    }
    FILE* writeFilePointer;
    if((writeFilePointer = fopen(writeFilePath, "w")) == NULL)
    {
        printf("Write File could not be opened at %s!\n", writeFilePath);
        exit(1);
    }

    // handling the header part of the file: before any major sections:
    CopyHeader(readFilePointer, writeFilePointer);
    // Atoms section:
    CopyAtomsSection(readFilePointer, writeFilePointer);
    //Velocities section:
    if(doesVelocitySectionExist)
        CopyVelocitiesSection(readFilePointer, writeFilePointer, skipVelocitiesSection);
    //Bonds Section:
    if(transFormArchitecture)
        GenerateBondsSection(writeFilePointer);
    else
        CopyBondsSection(readFilePointer, writeFilePointer);

    //closing file:
    fclose(readFilePointer);
    fclose(writeFilePointer);
}

void ReadAndWriteMixedStatesSeparately(const char* readFilePath, const char* writeFilePath1, const char* writeFilePath2, bool skipVelocitiesSection)
{
    // opening files:
    FILE* readFilePointer; 
    if((readFilePointer = fopen(readFilePath, "r")) == NULL)
    {
        printf("Read File could not be found at %s!\n", readFilePath);
        exit(1);
    }
    FILE* writeFilePointer1;
    if((writeFilePointer1 = fopen(writeFilePath1, "w")) == NULL)
    {
        printf("Write File could not be opened at %s!\n", writeFilePath1);
        exit(1);
    }
    FILE* writeFilePointer2;
    if((writeFilePointer2 = fopen(writeFilePath2, "w")) == NULL)
    {
        printf("Write File could not be opened at %s!\n", writeFilePath2);
        exit(1);
    }

    // copying the sections:
    CopyHeaderSectionSeparately(readFilePointer, writeFilePointer1, writeFilePointer2);
    CopyAtomsSectionSeparately(readFilePointer, writeFilePointer1, writeFilePointer2);
    if(doesVelocitySectionExist)
        CopyVelocitiesSectionSeparately(readFilePointer, writeFilePointer1, writeFilePointer2, skipVelocitiesSection);
    GenerateBondsSectionSeparately(writeFilePointer1);
    GenerateBondsSectionSeparately(writeFilePointer2);

    fclose(readFilePointer);
    fclose(writeFilePointer1);
    fclose(writeFilePointer2);
}


//compares two strings and returns their difference: debugging
int CompareStrings(const char* string1, const char* string2)
{
    return strcmp(string1, string2);
}

//Reads the mixed state file and generates the initial state for a particular run
void GenerateInitialState(int runNumber)
{
    char* readFilePath;
    char* writeFilePath;
    if(USE_CONFIG_PATHS)
    {
        readFilePath = SOURCE_PATH;
        writeFilePath = DEST_PATH;
    }
    else
    {
        SetReadFilePath(&readFilePath, runNumber);
        SetWriteFilePath(&writeFilePath, runNumber);
    }

    ReadAndWriteMixedState(readFilePath, writeFilePath, false);
    printf("Mixed configuration file copied for %s run %i to %s!\n", architecture, runNumber, writeFilePath);
    if(!USE_CONFIG_PATHS)
    {
        free(readFilePath);
        free(writeFilePath);
    }
}

//Reads the mixed state and generates two files for each of the polymers
void GenerateSeprateInitialStates(int runNumber)
{
    char* readFilePath;
    SetReadFilePath(&readFilePath, runNumber);
    currentIndexOfPolymer = 1;
    char* writeFilePath1;
    SetWriteFilePath(&writeFilePath1, runNumber);
    currentIndexOfPolymer = 2;
    char* writeFilePath2;
    SetWriteFilePath(&writeFilePath2, runNumber);
    ReadAndWriteMixedStatesSeparately(readFilePath, writeFilePath1, writeFilePath2, false);
    free(readFilePath);
    char* writeFileName;
    SetWriteFileName(&writeFileName);
    printf("Mixed configuration file copied for %s run %i to separate files %s and %s!\n", architecture, runNumber, writeFilePath1, writeFileName); 
    free(writeFilePath1);
    free(writeFilePath2);
    free(writeFileName);
}

int main(int argc, char** argv)
{
    SetConstants(argc, argv);
    // Reading cross links information:   
    InitializeArchitecture(&archCrossLinks, requiredArchitecture);
    char* databaseFilePath;
    SetCrossLinksDatabaseFilePath(&databaseFilePath, numberOfMonomers);
    ReadCrossLinks(&archCrossLinks, databaseFilePath);
    free(databaseFilePath);

    // printf("Number of Cross Links in %s : %i\n", architecture, numberOfCrossLinks);
    // printf("One example index: %i\n", crossLinks[numberOfCrossLinks - 1][1]);

    int numberOfRuns = 50;

    //checking if runNumber was provided as an argument:
    if(runNumber == -1) // runNumber was not provided; create states for all runs:
    {
        for(int runNumber = 1; runNumber <= numberOfRuns; runNumber++)
        {
            // int runNumber = 1;
            if(writeIndividualPolymerStates)
                GenerateSeprateInitialStates(runNumber);
            else
                GenerateInitialState(runNumber);
        }
    }
    else
    {
        if(runNumber > numberOfRuns || runNumber < 1) // checking validity of runNumber
        {
            printf("Please enter a run number between 1 and %i! Run %i does not exist.\n", numberOfRuns, runNumber);
            exit(1);
        }
        else
        {
            if(writeIndividualPolymerStates)
                GenerateSeprateInitialStates(runNumber);
            else
                GenerateInitialState(runNumber);
        }
    }

    //freeing some allocated memory:
    FreeArchitecture(&archCrossLinks);
    if(transFormArchitecture)
    {
        printf("Architecture %s mixed state file successfuly transformed to Architecture %s\n", architecture, requiredArchitecture);
    }
    free(requiredArchitecture);
}
