#!/bin/sh
# This script does the post processing of the data generated by the segregation simulations:
numberOfMonomers=$1
architecture=$2
runIndex=$3
special_simulation=$4 # The name of the initialization procedure
numberOfRuns=50

if [ -z ${numberOfMonomers} ] || [ -z ${architecture} ] || [ -z ${runIndex} ] || [ -z ${special_simulation} ]; then
	echo "Not enough arguments passed! Please pass the number of monomers, the architecture, the run index, and the name of the initialization procedure as arguments while invoking the script"
	echo "For example: $ execute_postProcessing.sh 200 Arc-0 1 fene_recenter"
	exit 1
fi

# Some directory paths:
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="$(cd $SCRIPT_DIR/../../ && pwd)/"

SEGREGATION="${BASE_DIR}Segregation/"
SCRIPTS="${BASE_DIR}Global_Scripts/"

# Setting the folderPrefix:
if ! [ -z ${special_simulation} ]; then
	folderPrefix=${special_simulation}/
	echo "Post processing the files in the folder ${folderPrefix}"
        folderPrefix=b${numberOfMonomers}/${special_simulation}/
        echo "Post processing the files in the special simulation folder '${folderPrefix}'."

else
	folderPrefix=b${numberOfMonomers}/
	echo "Post processing the files in the default New_Segregation/b${numberOfMonomers} location."
fi

# Reading the confinement diameter for the current architecture:
. ${SCRIPTS}bash_functions.sh # 'Importing' the bash functions file
diameterFileDir=${SEGREGATION}b${numberOfMonomers}/
if [[ ${special_simulation} == *"inf"* ]]; then # If the segregation needs to be done in an infinite cylinder
	diametersFile=${diameterFileDir}c_Diameters.csv # Path to the diameter database file for the infinite cylinder (constant confinement) simulations
else
	diametersFile=${diameterFileDir}Diameters.csv # Path to the diameter database file for the finite cylinder simulations
fi
# An empty dictionary that will be filled:
declare -A diameters=() 
read_diameters ${diametersFile} # Calling the function from bash_functions
error=$?
radius=$(bc <<< "scale=2; ${diameters[${architecture}]}/2")
error=$((error+$?))

echo "Confinement radius for ${architecture} = ${radius}"
if ! [ ${error} -eq 0 ] # checking if the above process ended in an error
then
        echo "A problem was encountered while reading the confinement diameters! Terminating."
        exit ${error}
fi
# Axis length:
if [[ ${special_simulation} == *"inf"* ]]; then # If the segregation needs to be done in an infinite cylinder
	axisLength="" # Empty string since the axis length is not defined for an infinite cylinder
else
	axisLength=$(bc <<< "scale=2; 10 * ${radius}")
fi


# compiling C scripts:
# regional monomer density:
gcc general_monomer_density.c -lm -std=gnu99 -o ge.out -I $BASE_DIR

# radial monomer density:
gcc radial_monomer_density.c -lm -std=gnu99 -o radial.out -I $BASE_DIR

# regional CoM time series:
gcc calculateCoMTimeSeries.c -lm -std=gnu99 -o com.out -I $BASE_DIR

i=${runIndex}
# for((i=1; i<=${numberOfRuns}; i++)) # Can be done for multiple runs simultaneously
# do
nohup bash postProcessing.sh ${numberOfMonomers} ${architecture} $i ${special_simulation} Segregation ${axisLength} > ../${folderPrefix}${architecture}/run$i/post_nohup.out &
sleep 1
# done
