#!/bin/sh
# This script does the post processing of the data generated by the segregation simulations:
architecture=$2
numberOfRuns=50
numberOfMonomers=$1
special_simulation=$3 # Optional argument for running the algorithms in a special folder

if [ -z ${numberOfMonomers} ] || [ -z ${architecture} ]
then
	echo "Not enough arguments passed! Please pass the number of monomers and the architecture as arguments to the command line."
	echo "Optionally, an argument for the special simulation folder can be passed after the two arguments."
	exit 1
fi

# Some directory paths:
SCRIPTS=/scratch/Harsh/Scripts/
NEW_SEGREGATION=/scratch/Harsh/New_Segregation/

# Setting the folderPrefix:
if ! [ -z ${special_simulation} ]; then
	folderPrefix=${special_simulation}/
	echo "Post processing the files in the folder ${folderPrefix}"
        folderPrefix=b${numberOfMonomers}/Previous_Attempts/${special_simulation}/
        echo "Post processing the files in the special simulation folder '${folderPrefix}'."

else
	folderPrefix=b${numberOfMonomers}/
	echo "Post processing the files in the default New_Segregation/b${numberOfMonomers} location."
fi

# correcting CoM data: only necessary if one is printing data during the Monte Carlo simulation
#gcc correctPrintOutput.c -lm -std=gnu99 -o correctOutput.out
#./correctOutput.out ${architecture} ${numberOfMonomers}
# renaming files:
#bash removeDuplicateCoMFiles.sh ${architecture} ${numberOfMonomers}

# Reading the confinement diameter for the current architecture:
. ${SCRIPTS}bash_functions.sh # 'Importing' the bash functions file
diametersFile=${NEW_SEGREGATION}b${numberOfMonomers}/Diameters.csv # Path to the diameter database file
# An empty dictionary that will be filled:
declare -A diameters=() 
read_diameters ${diametersFile} # Calling the function from bash_functions
error=$?
radius=$(bc <<< "scale=2; ${diameters[${architecture}]}/2")
error=$((error+$?))

echo "Confinement radius for ${architecture} = ${radius}"
if ! [ ${error} -eq 0 ] # checking if the above process ended in an error
then
        echo "A problem was encountered while reading the confinement diameters! Terminating."
        exit ${error}
fi
# Axis length:
axisLength=$(bc <<< "scale=2; 10 * ${radius}")

# compiling C scripts:
# regional monomer density:
gcc general_monomer_density.c -lm -std=gnu99 -o ge.out

# radial monomer density:
gcc radial_monomer_density.c -lm -std=gnu99 -o radial.out

# regional CoM time series:
gcc calculateCoMTimeSeries.c -lm -std=gnu99 -o com.out

for((i=1; i<=${numberOfRuns}; i++))
do
	nohup bash postProcessing.sh ${numberOfMonomers} ${architecture} $i ${axisLength} new_segregation > ../${folderPrefix}${architecture}/run$i/post_nohup.out &
	sleep 1
done
